name: Git Secrets Scan
on: push
jobs:
  scan:
    runs-on: ubuntu-latest
    name: Git Secrets Scanner
    steps:
    - uses: actions/checkout@v2
      with:
        repository: ${{github.repository}}
        path: repo
    - uses: actions/checkout@v2
      with:
        repository: Smarsh/git-secrets
        ref: master
        token: ${{ secrets.SECRETS_SCANNER_ACCESS_TOKEN }}
        path: git-secrets
    - id: install 
      run: cd $GITHUB_WORKSPACE/git-secrets && sudo make install
    - uses: actions/checkout@v2
      with:
        repository: Smarsh/Git-Secrets-Scanner
        ref: master
        token: ${{ secrets.SECRETS_SCANNER_ACCESS_TOKEN }}
        path: Git-Secrets-Scanner
    - id: setup
      run: cd $GITHUB_WORKSPACE/Git-Secrets-Scanner && bash ./install-action.sh
    - id: runhook
      run: cd $GITHUB_WORKSPACE/repo && git secrets --pre_commit_hook -- "$@"
